server.port=9090
server.servlet.context-path=/test-api
spring.application.name=backendjavaapi

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234567890